"""added images

Revision ID: c51408f12b7a
Revises: c6aaa806c251
Create Date: 2024-04-13 00:05:27.811977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51408f12b7a'
down_revision = 'c6aaa806c251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("ALTER TABLE motors ALTER COLUMN images TYPE JSON USING images::json")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.VARCHAR(), nullable=True))

    op.drop_table('images')
    # ### end Alembic commands ###
