"""no json

Revision ID: c6aaa806c251
Revises: c55cd8c4a6b5
Create Date: 2024-04-12 23:55:15.743858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c6aaa806c251'
down_revision = 'c55cd8c4a6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
